[Unit]
Requires=
Requires=silo-system-docker-preflight.service containerd.service
After=silo-system-docker-preflight.service containerd.service
StartLimitIntervalSec=30s
StartLimitBurst=3

[Service]
ExecStartPre=/usr/sbin/silo-system-activate check
ExecStart=
ExecStart=/usr/bin/dockerd --host=unix:///run/docker.sock --containerd=/run/containerd/containerd.sock
Restart=on-failure
RestartSec=2s
