#ifndef SILO_GO_FFI_H
#define SILO_GO_FFI_H

/* THIS FILE IS GENERATED BY cbindgen. DO NOT EDIT. Run `cargo build -p silo-go-ffi` to regenerate it. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct silo_execution silo_execution;

typedef struct silo_log silo_log;

typedef struct silo_machine silo_machine;

typedef struct silo_runtime silo_runtime;

typedef struct silo_stdin silo_stdin;

typedef struct {
  uint8_t *ptr;
  size_t len;
} silo_buffer;

typedef struct {
  char *variant;
  char *message;
} silo_error;

typedef struct {
  silo_buffer result;
  silo_buffer stdout_data;
  silo_buffer stderr_data;
  silo_buffer terminal_output;
} silo_execution_output;

typedef struct {
  silo_buffer metadata;
  silo_buffer data;
} silo_execution_event;

typedef struct {
  uint32_t output;
  silo_buffer data;
} silo_log_chunk;

typedef struct {
  silo_machine **ptr;
  size_t len;
} silo_machine_handle_list;

uint32_t silo_ffi_abi_version(void);

const char *silo_ffi_sdk_version(void);

/**
 * Frees a buffer returned by this bridge.
 *
 * # Safety
 * `buffer` must be an unmodified value returned by this exact bridge and must be freed once.
 */
void silo_buffer_free(silo_buffer buffer);

/**
 * Frees an error returned by this bridge.
 *
 * # Safety
 * `error` must be null or an unmodified pointer returned by this exact bridge and freed once.
 */
void silo_error_free(silo_error *error);

silo_error *silo_machine_exec(const silo_machine *machine,
                              const uint8_t *request_ptr,
                              size_t request_len,
                              silo_execution_output *out_output);

silo_error *silo_machine_shell(const silo_machine *machine,
                               const uint8_t *request_ptr,
                               size_t request_len,
                               silo_execution_output *out_output);

silo_error *silo_machine_spawn(const silo_machine *machine,
                               const uint8_t *request_ptr,
                               size_t request_len,
                               silo_execution **out_session);

silo_error *silo_machine_attach(const silo_machine *machine,
                                const uint8_t *request_ptr,
                                size_t request_len,
                                silo_buffer *out_result);

silo_error *silo_machine_attach_shell(const silo_machine *machine,
                                      const uint8_t *request_ptr,
                                      size_t request_len,
                                      silo_buffer *out_status);

silo_error *silo_execution_recv(const silo_execution *session,
                                silo_execution_event *out_event,
                                bool *out_eof);

silo_error *silo_execution_wait(const silo_execution *session, silo_buffer *out_result);

silo_error *silo_execution_collect(const silo_execution *session,
                                   silo_execution_output *out_output);

silo_error *silo_execution_stdin(const silo_execution *session, silo_stdin **out_stdin);

silo_error *silo_execution_signal(const silo_execution *session, uint32_t signal);

silo_error *silo_execution_resize_pty(const silo_execution *session,
                                      uint16_t rows,
                                      uint16_t columns);

silo_error *silo_execution_close_requests(const silo_execution *session);

silo_error *silo_execution_cancel(const silo_execution *session);

void silo_execution_free(silo_execution *session);

silo_error *silo_stdin_write(const silo_stdin *stdin, const uint8_t *data_ptr, size_t data_len);

silo_error *silo_stdin_close(const silo_stdin *stdin);

void silo_stdin_free(silo_stdin *stdin);

silo_error *silo_images_call(const silo_runtime *runtime,
                             const uint8_t *request_ptr,
                             size_t request_len,
                             silo_buffer *out_data);

silo_error *silo_machine_logs(const silo_machine *machine,
                              const uint8_t *request_ptr,
                              size_t request_len,
                              silo_log **out_log);

silo_error *silo_log_recv(const silo_log *log, silo_log_chunk *out_chunk, bool *out_eof);

silo_error *silo_log_close(const silo_log *log);

void silo_log_free(silo_log *log);

silo_error *silo_runtime_machine_create(const silo_runtime *runtime,
                                        const uint8_t *request_ptr,
                                        size_t request_len,
                                        silo_machine **out_machine);

silo_error *silo_machine_id(const silo_machine *machine, silo_buffer *out_id);

silo_error *silo_machine_inspect(const silo_machine *machine, silo_buffer *out_data);

silo_error *silo_machine_start(const silo_machine *machine, silo_buffer *out_data);

silo_error *silo_machine_stop(const silo_machine *machine, silo_buffer *out_data);

silo_error *silo_machine_remove(const silo_machine *machine);

silo_error *silo_network_policy_build(const uint8_t *request_ptr,
                                      size_t request_len,
                                      silo_buffer *out_policy);

silo_error *silo_runtime_open(const uint8_t *request_ptr,
                              size_t request_len,
                              silo_runtime **out_runtime);

void silo_runtime_free(silo_runtime *runtime);

silo_error *silo_runtime_machine_get(const silo_runtime *runtime,
                                     const uint8_t *reference_ptr,
                                     size_t reference_len,
                                     silo_machine **out_machine);

silo_error *silo_runtime_machines(const silo_runtime *runtime,
                                  silo_machine_handle_list *out_machines);

silo_machine *silo_machine_handle_list_at(const silo_machine_handle_list *machines, size_t index);

void silo_machine_handle_list_free(silo_machine_handle_list machines);

void silo_machine_free(silo_machine *machine);

#endif  /* SILO_GO_FFI_H */
