[workspace]
members = [
    "app/cli",
    "common/policy",
    "common/disk-image",
    "xtask",
    "common/utils",
    "guest/agent",
    "guest/init",
    "runtime/oci",
    "runtime/libvm",
    "runtime/test-utils",
    "runtime/vmmon",
    "sdk/node",
    "sdk/go/native",
    "virt/krun",
    "virt/vhost-vsock",
    "virt/vz",
    "specs/agent-spec",
    "specs/forward-spec",
    "specs/protocol",
    "specs/vm-spec",
]
default-members = ["app/cli", "runtime/vmmon"]
resolver = "2"

[workspace.dependencies]
libkrun = { package = "libkrun", git = "https://github.com/vandycknick/libkrun.git", rev = "10b6f752ba8ea735c3d9edaa549599dcf3f98d18", default-features = false, features = ["blk", "net"] }

[profile.dev.package.sha2]
opt-level = 3
