#ifndef BENTO_POLICY_H
#define BENTO_POLICY_H

/* Generated with cbindgen:0.29.4 */

/* Generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
typedef struct bento_policy_t bento_policy_t;
typedef struct bento_policy_http_context_t bento_policy_http_context_t;


typedef uint32_t bento_policy_status_t;

typedef struct bento_policy_bytes_t {
  const uint8_t *ptr;
  size_t len;
} bento_policy_bytes_t;

typedef struct bento_policy_buffer_t {
  uint8_t *ptr;
  size_t len;
} bento_policy_buffer_t;

#define BENTO_POLICY_OK 0

#define BENTO_POLICY_LOAD_ERROR 1

#define BENTO_POLICY_INVALID_ARGUMENT 2

#define BENTO_POLICY_EVAL_ERROR 3

#define BENTO_POLICY_PANIC 255

bento_policy_status_t bento_policy_parse_source(struct bento_policy_bytes_t filename,
                                                struct bento_policy_bytes_t source,
                                                struct bento_policy_t **out_policy,
                                                struct bento_policy_buffer_t *out_error_json);

bento_policy_status_t bento_policy_snapshot_json(const struct bento_policy_t *policy,
                                                 struct bento_policy_buffer_t *out_json);

bento_policy_status_t bento_policy_http_context_from_json(struct bento_policy_bytes_t input_json,
                                                          struct bento_policy_http_context_t **out_context,
                                                          struct bento_policy_buffer_t *out_error_json);

bento_policy_status_t bento_policy_http_condition_evaluate(const struct bento_policy_t *policy,
                                                           uint32_t condition_id,
                                                           const struct bento_policy_http_context_t *context,
                                                           bool *out_matches,
                                                           struct bento_policy_buffer_t *out_error_json);

void bento_policy_free(struct bento_policy_t *policy);

void bento_policy_http_context_free(struct bento_policy_http_context_t *context);

void bento_policy_buffer_free(struct bento_policy_buffer_t buffer);

#endif  /* BENTO_POLICY_H */
