use std::collections::BTreeMap;
use std::fs;
use std::os::unix::fs::{DirBuilderExt, PermissionsExt};
use std::path::{Path, PathBuf};

use vm_spec::{Boot, Disk, Guest, GuestOs, Hardware, Kernel, Mount, Storage, VmSpec};

use crate::image::{ImageBuilder, ImageSource, MaterializedImage};
use crate::lock_manager::ManagedLock;
use crate::machine::root_disk::{clone_or_copy_root_disk, resize_raw_disk};
use crate::machine::{
    generate_machine_name, validate_machine_name, GuestBuilder, Machine, MachineGuestConfig, Memory,
};
use crate::network::{MachineNetworkBuilder, MachineNetworkConfig};
use crate::paths::{root_disk_relative_path, MachinePaths};
use crate::runtime::core::{stopped_machine_state, write_machine_config};
use crate::runtime::Runtime;
use crate::store::models::{
    MachineConfig, MachineId, MachineNetworkConfig as ModelMachineNetworkConfig,
    MachineRootfsRecord,
};
use crate::utils::now_unix;
use crate::LibVmError;

const DEFAULT_IMAGE_CPUS: u8 = 1;
const DEFAULT_IMAGE_MEMORY_MIB: u32 = 512;
const ROOT_DISK_KERNEL_ARG: &str = "root=/dev/vda";
const GENERATED_NAME_ATTEMPTS: u32 = 3;

#[derive(Debug, Clone)]
struct MachineCreateRequest {
    image_source: Option<ImageSource>,
    name: Option<String>,
    labels: BTreeMap<String, String>,
    metadata: BTreeMap<String, String>,
    cpus: Option<u8>,
    memory: Option<Memory>,
    kernel: Option<PathBuf>,
    initramfs: Option<PathBuf>,
    disk_size_bytes: Option<u64>,
    nested_virtualization: bool,
    rosetta: bool,
    userdata: Option<String>,
    disks: Vec<PathBuf>,
    mounts: Vec<Mount>,
    network: Option<MachineNetworkConfig>,
    network_error: Option<String>,
    guest: MachineGuestConfig,
}

struct MachineCreatePlan {
    name: String,
    spec: VmSpec,
    labels: BTreeMap<String, String>,
    metadata: BTreeMap<String, String>,
    network: ModelMachineNetworkConfig,
    guest: MachineGuestConfig,
}

struct MachineCreateGuard {
    id: MachineId,
    name: String,
    spec: VmSpec,
    machine_dir: PathBuf,
    lock: Option<ManagedLock>,
    labels: BTreeMap<String, String>,
    metadata: BTreeMap<String, String>,
    network: ModelMachineNetworkConfig,
    guest: MachineGuestConfig,
    dir_created: bool,
    committed: bool,
}

/// Builder for creating a machine.
///
/// The builder records durable desired configuration. It does not start vmmon or
/// prepare networking. Those runtime artifacts are regenerated by `Machine::start`.
/// Image materialization happens during `create`; `Machine::start` only boots the
/// already-created root disk.
///
/// ```rust,no_run
/// use libvm::{ImageSource, Memory, Runtime};
///
/// # async fn example(runtime: Runtime) -> Result<(), libvm::LibVmError> {
/// let machine = runtime
///     .machine()
///     .image("docker.io/library/alpine:latest")
///     .name("devbox")
///     .cpus(4)
///     .memory(Memory::gibibytes(8))
///     .network(|network| network.private())
///     .create()
///     .await?;
/// let from_disk = runtime
///     .machine()
///     .image_source(ImageSource::disk("/tmp/rootfs.img"))
///     .create()
///     .await?;
/// # let _ = from_disk;
/// # let _ = machine;
/// # Ok(())
/// # }
/// ```
pub struct MachineBuilder {
    runtime: Runtime,
    request: MachineCreateRequest,
}

impl MachineBuilder {
    pub(crate) fn new(runtime: Runtime) -> Self {
        Self {
            runtime,
            request: MachineCreateRequest {
                image_source: None,
                name: None,
                labels: BTreeMap::new(),
                metadata: BTreeMap::new(),
                cpus: None,
                memory: None,
                kernel: None,
                initramfs: None,
                disk_size_bytes: None,
                nested_virtualization: false,
                rosetta: false,
                userdata: None,
                disks: Vec::new(),
                mounts: Vec::new(),
                network: None,
                network_error: None,
                guest: MachineGuestConfig::default(),
            },
        }
    }

    /// Selects an OCI image reference for this machine.
    ///
    /// The string is always interpreted as OCI. Use `image_source` or
    /// `image_with` for local disk and tar sources.
    pub fn image(mut self, reference: impl Into<String>) -> Self {
        self.request.image_source = Some(ImageSource::oci(reference));
        self
    }

    /// Selects an explicit image source.
    pub fn image_source(mut self, source: ImageSource) -> Self {
        self.request.image_source = Some(source);
        self
    }

    /// Selects an image source using a dedicated image builder.
    pub fn image_with(mut self, configure: impl FnOnce(ImageBuilder) -> ImageBuilder) -> Self {
        self.request.image_source = configure(ImageBuilder::new()).finish();
        self
    }

    /// Sets an explicit machine name.
    pub fn name(mut self, name: impl Into<String>) -> Self {
        self.request.name = Some(name.into());
        self
    }

    /// Replaces all labels.
    pub fn labels(mut self, labels: BTreeMap<String, String>) -> Self {
        self.request.labels = labels;
        self
    }

    /// Adds one label.
    pub fn label(mut self, key: impl Into<String>, value: impl Into<String>) -> Self {
        self.request.labels.insert(key.into(), value.into());
        self
    }

    /// Replaces all metadata.
    pub fn metadata(mut self, metadata: BTreeMap<String, String>) -> Self {
        self.request.metadata = metadata;
        self
    }

    /// Adds one metadata entry.
    pub fn metadata_entry(mut self, key: impl Into<String>, value: impl Into<String>) -> Self {
        self.request.metadata.insert(key.into(), value.into());
        self
    }

    /// Sets the virtual CPU count.
    pub fn cpus(mut self, cpus: u8) -> Self {
        self.request.cpus = Some(cpus);
        self
    }

    /// Sets the machine memory.
    pub fn memory(mut self, memory: Memory) -> Self {
        self.request.memory = Some(memory);
        self
    }

    /// Sets a kernel path override.
    pub fn kernel(mut self, kernel: impl Into<PathBuf>) -> Self {
        self.request.kernel = Some(kernel.into());
        self
    }

    /// Sets an initramfs path override.
    pub fn initramfs(mut self, initramfs: impl Into<PathBuf>) -> Self {
        self.request.initramfs = Some(initramfs.into());
        self
    }

    /// Configures durable guest behavior outside the VMM specification.
    pub fn guest(mut self, configure: impl FnOnce(GuestBuilder) -> GuestBuilder) -> Self {
        self.request.guest = configure(GuestBuilder::new()).build();
        self
    }

    /// Sets the desired root disk size in bytes.
    pub fn root_disk_size(mut self, bytes: u64) -> Self {
        self.request.disk_size_bytes = Some(bytes);
        self
    }

    /// Enables or disables nested virtualization.
    pub fn nested_virtualization(mut self, enabled: bool) -> Self {
        self.request.nested_virtualization = enabled;
        self
    }

    /// Enables or disables Rosetta support.
    pub fn rosetta(mut self, enabled: bool) -> Self {
        self.request.rosetta = enabled;
        self
    }

    /// Sets guest userdata.
    pub fn userdata(mut self, userdata: impl Into<String>) -> Self {
        self.request.userdata = Some(userdata.into());
        self
    }

    /// Replaces additional disk paths.
    pub fn disks(mut self, disks: Vec<PathBuf>) -> Self {
        self.request.disks = disks;
        self
    }

    /// Replaces guest mounts.
    pub fn mounts(mut self, mounts: Vec<Mount>) -> Self {
        self.request.mounts = mounts;
        self
    }

    /// Configures the durable network attachment.
    pub fn network(
        mut self,
        configure: impl FnOnce(MachineNetworkBuilder) -> MachineNetworkBuilder,
    ) -> Self {
        match configure(MachineNetworkBuilder::new()).build() {
            Ok(network) => self.request.network = Some(network),
            Err(reason) => self.request.network_error = Some(reason),
        }
        self
    }

    /// Creates the machine.
    pub async fn create(self) -> Result<Machine, LibVmError> {
        let runtime = self.runtime;
        let config = create_machine_config(&runtime, self.request).await?;
        Ok(Machine::new(runtime.without_image_progress(), config.id))
    }
}

async fn create_machine_config(
    runtime: &Runtime,
    request: MachineCreateRequest,
) -> Result<MachineConfig, LibVmError> {
    let Some(name) = request.name.clone() else {
        return create_machine_config_with_generated_name(runtime, request).await;
    };

    create_machine_config_with_name(runtime, request, name).await
}

async fn create_machine_config_with_generated_name(
    runtime: &Runtime,
    request: MachineCreateRequest,
) -> Result<MachineConfig, LibVmError> {
    for _ in 0..GENERATED_NAME_ATTEMPTS {
        let name = generate_machine_name()?;
        match create_machine_config_with_name(runtime, request.clone(), name).await {
            Err(LibVmError::MachineAlreadyExists { .. }) => {}
            result => return result,
        }
    }

    Err(LibVmError::MachineNameGenerationFailed {
        attempts: GENERATED_NAME_ATTEMPTS,
    })
}

async fn create_machine_config_with_name(
    runtime: &Runtime,
    mut request: MachineCreateRequest,
    name: String,
) -> Result<MachineConfig, LibVmError> {
    if matches!(request.disk_size_bytes, Some(0)) {
        return Err(LibVmError::InvalidCreateRequest {
            name,
            reason: "root disk size must be greater than 0".to_string(),
        });
    }
    let Some(image_source) = request.image_source.clone() else {
        return Err(LibVmError::InvalidCreateRequest {
            name,
            reason: "machine image source is required".to_string(),
        });
    };
    if let Some(reason) = request.network_error {
        return Err(LibVmError::InvalidCreateRequest { name, reason });
    }
    if let Some(user) = &request.guest.user {
        user.validate()
            .map_err(|reason| LibVmError::InvalidCreateRequest {
                name: name.clone(),
                reason,
            })?;
    }

    let (kernel, initramfs) = crate::runtime::boot_assets::canonicalize_boot_overrides(
        crate::runtime::boot_assets::BootAssetOverrides {
            kernel: request.kernel.as_deref(),
            initramfs: request.initramfs.as_deref(),
        },
    )?;
    request.guest = crate::runtime::boot_assets::canonicalize_guest_config(request.guest)?;
    if let Some(userdata) = request.userdata.as_deref() {
        if userdata.trim().is_empty() {
            return Err(LibVmError::InvalidCreateRequest {
                name,
                reason: "userdata cannot be empty".to_string(),
            });
        }
    }
    let userdata = request.userdata;
    let disk_paths = canonicalize_existing_paths(&request.disks, "disk")?;

    let resolved_cpus = request.cpus.unwrap_or(DEFAULT_IMAGE_CPUS);
    let resolved_memory = request
        .memory
        .map(|memory| memory.to_vm_spec_mebibytes(&name))
        .transpose()?
        .unwrap_or(DEFAULT_IMAGE_MEMORY_MIB);

    let mounts = assign_mount_tags(request.mounts);
    let disks = std::iter::once(Disk {
        path: root_disk_relative_path(),
        read_only: false,
    })
    .chain(disk_paths.into_iter().map(|path| Disk {
        path,
        read_only: false,
    }))
    .collect();

    let spec = VmSpec {
        guest: Some(Guest {
            os: Some(GuestOs::Linux),
        }),
        boot: Some(Boot {
            kernel: Some(Kernel {
                path: kernel,
                cmdline: vec![ROOT_DISK_KERNEL_ARG.to_string()],
                initramfs,
            }),
            userdata,
        }),
        hardware: Some(Hardware {
            cpus: Some(resolved_cpus),
            memory: Some(resolved_memory),
            nested_virtualization: Some(request.nested_virtualization),
            rosetta: Some(request.rosetta),
        }),
        storage: Some(Storage { disks }),
        mounts,
        ..VmSpec::current()
    };

    let network = request.network.unwrap_or_default().into();
    runtime.validate_machine_network_config(&network).await?;
    let create = create_machine_guard(
        runtime,
        MachineCreatePlan {
            name,
            spec,
            labels: request.labels,
            metadata: request.metadata,
            network,
            guest: request.guest,
        },
    )
    .await?;

    let materialized = runtime.materialize_image(&image_source).await?;
    let root_disk_size = request.disk_size_bytes.unwrap_or(materialized.size_bytes);
    if root_disk_size == 0 {
        return Err(LibVmError::InvalidCreateRequest {
            name: create.name.clone(),
            reason: "root disk size must be greater than 0".to_string(),
        });
    }
    let rootfs_path = MachinePaths::new(create.dir()).root_disk_path();
    clone_or_copy_root_disk(&materialized.rootfs_path, &rootfs_path)?;

    if let Some(size_bytes) = request.disk_size_bytes {
        resize_raw_disk(&rootfs_path, size_bytes)?;
    }

    let rootfs = machine_rootfs_record(&create, &materialized, rootfs_path, root_disk_size);
    create
        .commit(
            runtime,
            rootfs,
            materialized.image_ref,
            Some(root_disk_size),
        )
        .await
}

async fn create_machine_guard(
    runtime: &Runtime,
    plan: MachineCreatePlan,
) -> Result<MachineCreateGuard, LibVmError> {
    let MachineCreatePlan {
        name,
        spec,
        labels,
        metadata,
        network,
        guest,
    } = plan;

    validate_machine_name(&name)?;

    if runtime
        .machine_config_by_name(name.as_str())
        .await?
        .is_some()
    {
        return Err(LibVmError::MachineAlreadyExists { name });
    }

    let id = MachineId::new();
    let machine_dir = runtime.machine_paths(id).dir().to_path_buf();
    let lock = runtime.allocate_machine_lock()?;
    let mut create = MachineCreateGuard {
        id,
        name,
        spec,
        machine_dir,
        lock: Some(lock),
        labels,
        metadata,
        network,
        guest,
        dir_created: false,
        committed: false,
    };

    create.create_machine_dir()?;
    write_machine_config(create.dir(), &create.name, &create.spec)?;

    Ok(create)
}

fn assign_mount_tags(mounts: Vec<Mount>) -> Vec<Mount> {
    mounts
        .into_iter()
        .enumerate()
        .map(|(index, mut mount)| {
            if mount.tag.trim().is_empty() {
                mount.tag = format!("mount{index}");
            }
            mount
        })
        .collect()
}

fn canonicalize_existing_paths(paths: &[PathBuf], kind: &str) -> Result<Vec<PathBuf>, LibVmError> {
    paths
        .iter()
        .map(|path| canonicalize_existing_path(path, kind))
        .collect()
}

fn canonicalize_existing_path(path: &Path, kind: &str) -> Result<PathBuf, LibVmError> {
    let abs = if path.is_absolute() {
        path.to_path_buf()
    } else {
        std::env::current_dir()?.join(path)
    };

    std::fs::canonicalize(&abs).map_err(|err| LibVmError::InvalidCreateRequest {
        name: kind.to_string(),
        reason: format!("{kind} path does not exist: {} ({err})", abs.display()),
    })
}

fn machine_rootfs_record(
    create: &MachineCreateGuard,
    image: &MaterializedImage,
    root_disk_path: PathBuf,
    root_disk_size_bytes: u64,
) -> MachineRootfsRecord {
    MachineRootfsRecord {
        machine_id: create.id,
        source_kind: image.source_kind,
        source_reference: image.source_reference.clone(),
        manifest_digest: image.manifest_digest.clone(),
        image_id: image.image_id.clone(),
        root_disk_path,
        root_disk_size_bytes,
        created_at: now_unix(),
    }
}

impl MachineCreateGuard {
    fn dir(&self) -> &Path {
        &self.machine_dir
    }

    fn create_machine_dir(&mut self) -> Result<(), LibVmError> {
        if let Some(parent) = self.machine_dir.parent() {
            fs::create_dir_all(parent)?;
        }
        let mut builder = fs::DirBuilder::new();
        builder.mode(0o700);
        match builder.create(&self.machine_dir) {
            Ok(()) => {
                self.dir_created = true;
                fs::set_permissions(&self.machine_dir, fs::Permissions::from_mode(0o700))?;
                Ok(())
            }
            Err(err) if err.kind() == std::io::ErrorKind::AlreadyExists => {
                Err(LibVmError::MachineIdAlreadyExists {
                    id: self.id.to_string(),
                })
            }
            Err(err) => Err(err.into()),
        }
    }

    async fn commit(
        mut self,
        runtime: &Runtime,
        rootfs: MachineRootfsRecord,
        image_ref: String,
        root_disk_size: Option<u64>,
    ) -> Result<MachineConfig, LibVmError> {
        let config = self.config(image_ref, root_disk_size);
        let initial_state = stopped_machine_state(self.id, None);
        runtime
            .add_machine_record_with_rootfs(&config, &initial_state, &rootfs)
            .await?;

        self.committed = true;
        Ok(config)
    }

    fn config(&self, image_ref: String, root_disk_size: Option<u64>) -> MachineConfig {
        let now = now_unix();
        MachineConfig {
            id: self.id,
            lock_id: self
                .lock
                .as_ref()
                .expect("machine create guard must hold allocated lock")
                .id(),
            name: self.name.clone(),
            spec: self.spec.clone(),
            machine_dir: self.machine_dir.clone(),
            created_at: now,
            modified_at: now,
            image_ref,
            root_disk_size,
            labels: self.labels.clone(),
            metadata: self.metadata.clone(),
            network: self.network.clone(),
            guest: self.guest.clone(),
        }
    }
}

impl Drop for MachineCreateGuard {
    fn drop(&mut self) {
        if self.committed {
            return;
        }

        if self.dir_created {
            match fs::remove_dir_all(&self.machine_dir) {
                Ok(()) => {}
                Err(err) if err.kind() == std::io::ErrorKind::NotFound => {}
                Err(_) => {}
            }
        }

        if let Some(lock) = self.lock.take() {
            let _ = lock.free();
        }
    }
}

#[cfg(test)]
mod tests {
    use std::os::unix::fs::PermissionsExt;
    use std::path::{Path, PathBuf};
    use std::sync::Arc;

    use vm_spec::{Boot, Guest, GuestOs, Hardware, Kernel, Mount, VmSpec};

    use crate::machine::builder::{
        assign_mount_tags, create_machine_config, create_machine_guard, MachineCreateGuard,
        MachineCreatePlan, MachineCreateRequest, ROOT_DISK_KERNEL_ARG,
    };
    use crate::paths::{root_disk_relative_path, LocalPaths};
    use crate::runtime::Runtime;
    use crate::store::models::{MachineId, MachineNetworkConfig, MachineRootfsRecord};
    use crate::store::MockDataStore;
    use crate::{ImageSource, LibVmError, Memory, RuntimeNetworkingConfig};

    fn sample_vm_spec() -> VmSpec {
        VmSpec {
            guest: Some(Guest {
                os: Some(GuestOs::Linux),
            }),
            boot: Some(Boot {
                kernel: Some(Kernel {
                    path: None,
                    cmdline: Vec::new(),
                    initramfs: None,
                }),
                userdata: None,
            }),
            hardware: Some(Hardware {
                cpus: Some(4),
                memory: Some(4096),
                nested_virtualization: Some(false),
                rosetta: Some(false),
            }),
            ..VmSpec::current()
        }
    }

    fn spec_kernel(spec: &VmSpec) -> &Kernel {
        spec.boot
            .as_ref()
            .and_then(|boot| boot.kernel.as_ref())
            .expect("spec should have kernel section")
    }

    fn spec_hardware(spec: &VmSpec) -> &Hardware {
        spec.hardware
            .as_ref()
            .expect("spec should have hardware section")
    }

    fn expect_empty_refresh(store: &mut MockDataStore) {
        store
            .expect_list_machine_configs()
            .once()
            .returning(|| Ok(Vec::new()));
    }

    async fn runtime_with_mock_store(paths: LocalPaths, store: MockDataStore) -> Runtime {
        Runtime::from_store(
            paths,
            Arc::new(store),
            RuntimeNetworkingConfig::default(),
            None,
        )
        .await
        .expect("create runtime with mock store")
    }

    async fn create_guard_sample(
        runtime: &Runtime,
        name: &str,
    ) -> Result<MachineCreateGuard, LibVmError> {
        create_machine_guard(
            runtime,
            MachineCreatePlan {
                name: name.to_string(),
                spec: sample_vm_spec(),
                labels: std::collections::BTreeMap::new(),
                metadata: std::collections::BTreeMap::new(),
                network: crate::store::models::MachineNetworkConfig::default(),
                guest: crate::machine::MachineGuestConfig::default(),
            },
        )
        .await
    }

    fn create_request(base_rootfs_path: PathBuf, name: &str) -> MachineCreateRequest {
        let boot_dir = base_rootfs_path
            .parent()
            .expect("rootfs has parent")
            .join("boot-assets");
        std::fs::create_dir_all(&boot_dir).expect("create boot assets dir");
        let kernel = boot_dir.join("kernel-default");
        let initramfs = boot_dir.join("initramfs");
        std::fs::write(&kernel, b"kernel").expect("write kernel");
        std::fs::write(&initramfs, b"initramfs").expect("write initramfs");

        MachineCreateRequest {
            image_source: Some(ImageSource::disk(base_rootfs_path)),
            name: Some(name.to_string()),
            labels: std::collections::BTreeMap::new(),
            metadata: std::collections::BTreeMap::new(),
            cpus: None,
            memory: None,
            kernel: Some(kernel),
            initramfs: Some(initramfs),
            disk_size_bytes: None,
            nested_virtualization: false,
            rosetta: false,
            userdata: None,
            disks: Vec::new(),
            mounts: Vec::new(),
            network: None,
            network_error: None,
            guest: crate::machine::MachineGuestConfig::default(),
        }
    }

    fn rootfs_record(create: &MachineCreateGuard) -> MachineRootfsRecord {
        MachineRootfsRecord {
            machine_id: create.id,
            source_kind: crate::ImageSourceKind::Disk,
            source_reference: "/tmp/rootfs.img".to_string(),
            manifest_digest: None,
            image_id: None,
            root_disk_path: create.dir().join(root_disk_relative_path()),
            root_disk_size_bytes: 4,
            created_at: 1,
        }
    }

    fn write_base_rootfs(data_dir: &Path) -> PathBuf {
        let image_dir = data_dir.join("images/sha256-test/linux-arm64");
        std::fs::create_dir_all(&image_dir).expect("image dir should be created");
        let base_rootfs_path = image_dir.join("rootfs.img");
        std::fs::write(&base_rootfs_path, b"disk").expect("rootfs should be written");
        base_rootfs_path
    }

    fn write_base_rootfs_with_size(data_dir: &Path, size: u64) -> PathBuf {
        let image_dir = data_dir.join("images/sha256-test/linux-arm64");
        std::fs::create_dir_all(&image_dir).expect("image dir should be created");
        let base_rootfs_path = image_dir.join("rootfs.img");
        let file = std::fs::File::create(&base_rootfs_path).expect("rootfs should be created");
        file.set_len(size).expect("rootfs size should be set");
        base_rootfs_path
    }

    #[tokio::test]
    async fn create_machine_config_clones_root_disk_and_sets_defaults() {
        let temp = tempfile::tempdir().expect("tempdir");
        let paths = LocalPaths::new(temp.path().join("silo"));
        let mut store = MockDataStore::new();
        expect_empty_refresh(&mut store);
        store
            .expect_machine_config_by_name()
            .withf(|name| name == "devbox")
            .once()
            .returning(|_| Ok(None));
        store
            .expect_add_machine_with_rootfs()
            .once()
            .returning(|_, _, _| Ok(()));
        let runtime = runtime_with_mock_store(paths, store).await;
        let base_rootfs_path = write_base_rootfs(temp.path());

        let mut request = create_request(base_rootfs_path, "devbox");
        request.kernel = None;
        request.initramfs = None;
        let machine = create_machine_config(&runtime, request)
            .await
            .expect("machine should be created");

        let root_disk = machine.machine_dir.join(root_disk_relative_path());
        assert!(root_disk.exists());
        assert_eq!(machine.name, "devbox");
        assert_eq!(spec_hardware(&machine.spec).cpus, Some(1));
        assert_eq!(spec_hardware(&machine.spec).memory, Some(512));
        assert_eq!(
            spec_kernel(&machine.spec).cmdline,
            vec![ROOT_DISK_KERNEL_ARG.to_string()]
        );
        assert!(spec_kernel(&machine.spec).path.is_none());
        assert!(spec_kernel(&machine.spec).initramfs.is_none());
        assert_eq!(machine.root_disk_size, Some(4));
    }

    #[tokio::test]
    async fn create_machine_config_generates_name_when_missing() {
        let temp = tempfile::tempdir().expect("tempdir");
        let paths = LocalPaths::new(temp.path().join("silo"));
        let mut store = MockDataStore::new();
        expect_empty_refresh(&mut store);
        store
            .expect_machine_config_by_name()
            .once()
            .returning(|_| Ok(None));
        store
            .expect_add_machine_with_rootfs()
            .once()
            .returning(|_, _, _| Ok(()));
        let runtime = runtime_with_mock_store(paths, store).await;
        let base_rootfs_path = write_base_rootfs(temp.path());
        let mut request = create_request(base_rootfs_path, "ignored");
        request.name = None;

        let config = create_machine_config(&runtime, request)
            .await
            .expect("machine should be created");

        crate::machine::validate_machine_name(&config.name).expect("generated name is valid");
    }

    #[tokio::test]
    async fn create_machine_config_retries_generated_name_conflicts() {
        let temp = tempfile::tempdir().expect("tempdir");
        let paths = LocalPaths::new(temp.path().join("silo"));
        let mut store = MockDataStore::new();
        expect_empty_refresh(&mut store);
        store
            .expect_machine_config_by_name()
            .times(2)
            .returning(|name| {
                if name.contains("-") {
                    static SEEN: std::sync::atomic::AtomicBool =
                        std::sync::atomic::AtomicBool::new(false);
                    if !SEEN.swap(true, std::sync::atomic::Ordering::SeqCst) {
                        return Ok(Some(crate::store::models::MachineConfig {
                            id: MachineId::new(),
                            lock_id: crate::lock_manager::LockId::from(0),
                            name: name.to_string(),
                            spec: VmSpec::current(),
                            machine_dir: PathBuf::from("/tmp/existing"),
                            created_at: 1,
                            modified_at: 1,
                            image_ref: "image".to_string(),
                            root_disk_size: None,
                            labels: std::collections::BTreeMap::new(),
                            metadata: std::collections::BTreeMap::new(),
                            network: MachineNetworkConfig::default(),
                            guest: crate::machine::MachineGuestConfig::default(),
                        }));
                    }
                }
                Ok(None)
            });
        store
            .expect_add_machine_with_rootfs()
            .once()
            .returning(|_, _, _| Ok(()));
        let runtime = runtime_with_mock_store(paths, store).await;
        let base_rootfs_path = write_base_rootfs(temp.path());
        let mut request = create_request(base_rootfs_path, "ignored");
        request.name = None;

        let config = create_machine_config(&runtime, request)
            .await
            .expect("machine should be created after retry");

        crate::machine::validate_machine_name(&config.name).expect("generated name is valid");
    }

    #[tokio::test]
    async fn create_machine_config_respects_requested_resources() {
        let temp = tempfile::tempdir().expect("tempdir");
        let paths = LocalPaths::new(temp.path().join("silo"));
        let mut store = MockDataStore::new();
        expect_empty_refresh(&mut store);
        store
            .expect_machine_config_by_name()
            .once()
            .returning(|_| Ok(None));
        store
            .expect_add_machine_with_rootfs()
            .once()
            .returning(|_, _, _| Ok(()));
        let runtime = runtime_with_mock_store(paths, store).await;
        let base_rootfs_path = write_base_rootfs(temp.path());
        let mut request = create_request(base_rootfs_path, "devbox");
        request.cpus = Some(4);
        request.memory = Some(Memory::gibibytes(8));
        request.nested_virtualization = true;
        request.rosetta = true;

        let config = create_machine_config(&runtime, request)
            .await
            .expect("machine should be created");

        let hardware = spec_hardware(&config.spec);
        assert_eq!(hardware.cpus, Some(4));
        assert_eq!(hardware.memory, Some(8192));
        assert_eq!(hardware.nested_virtualization, Some(true));
        assert_eq!(hardware.rosetta, Some(true));
    }

    #[tokio::test]
    async fn create_machine_config_rounds_memory_bytes_up_to_mebibytes() {
        let temp = tempfile::tempdir().expect("tempdir");
        let paths = LocalPaths::new(temp.path().join("silo"));
        let mut store = MockDataStore::new();
        expect_empty_refresh(&mut store);
        store
            .expect_machine_config_by_name()
            .once()
            .returning(|_| Ok(None));
        store
            .expect_add_machine_with_rootfs()
            .once()
            .returning(|_, _, _| Ok(()));
        let runtime = runtime_with_mock_store(paths, store).await;
        let base_rootfs_path = write_base_rootfs(temp.path());
        let mut request = create_request(base_rootfs_path, "devbox");
        request.memory = Some(Memory::bytes(1));

        let config = create_machine_config(&runtime, request)
            .await
            .expect("machine should be created");

        assert_eq!(spec_hardware(&config.spec).memory, Some(1));
    }

    #[tokio::test]
    async fn create_machine_config_rejects_zero_memory() {
        let temp = tempfile::tempdir().expect("tempdir");
        let paths = LocalPaths::new(temp.path().join("silo"));
        let mut store = MockDataStore::new();
        expect_empty_refresh(&mut store);
        let runtime = runtime_with_mock_store(paths, store).await;
        let base_rootfs_path = write_base_rootfs(temp.path());
        let mut request = create_request(base_rootfs_path, "devbox");
        request.memory = Some(Memory::bytes(0));

        let err = create_machine_config(&runtime, request)
            .await
            .expect_err("zero memory should be rejected");

        assert!(matches!(err, LibVmError::InvalidCreateRequest { .. }));
    }

    #[tokio::test]
    async fn create_machine_config_rejects_zero_root_disk_size() {
        let temp = tempfile::tempdir().expect("tempdir");
        let paths = LocalPaths::new(temp.path().join("silo"));
        let mut store = MockDataStore::new();
        expect_empty_refresh(&mut store);
        let runtime = runtime_with_mock_store(paths, store).await;
        let base_rootfs_path = write_base_rootfs(temp.path());
        let mut request = create_request(base_rootfs_path, "devbox");
        request.disk_size_bytes = Some(0);

        let err = create_machine_config(&runtime, request)
            .await
            .expect_err("zero disk should be rejected");

        assert!(matches!(err, LibVmError::InvalidCreateRequest { .. }));
    }

    #[tokio::test]
    async fn create_machine_config_resizes_root_disk_when_requested() {
        let temp = tempfile::tempdir().expect("tempdir");
        let paths = LocalPaths::new(temp.path().join("silo"));
        let mut store = MockDataStore::new();
        expect_empty_refresh(&mut store);
        store
            .expect_machine_config_by_name()
            .once()
            .returning(|_| Ok(None));
        store
            .expect_add_machine_with_rootfs()
            .once()
            .returning(|_, _, _| Ok(()));
        let runtime = runtime_with_mock_store(paths, store).await;
        let base_rootfs_path = write_base_rootfs_with_size(temp.path(), 4);
        let mut request = create_request(base_rootfs_path, "devbox");
        request.disk_size_bytes = Some(8);

        let config = create_machine_config(&runtime, request)
            .await
            .expect("machine should be created");

        let root_disk = config.machine_dir.join(root_disk_relative_path());
        assert_eq!(
            std::fs::metadata(root_disk)
                .expect("root disk metadata")
                .len(),
            8
        );
        assert_eq!(config.root_disk_size, Some(8));
    }

    #[tokio::test]
    async fn create_guard_and_commit_write_vm_spec_and_state() {
        let temp = tempfile::tempdir().expect("tempdir");
        let paths = LocalPaths::new(temp.path().join("silo"));
        let mut store = MockDataStore::new();
        expect_empty_refresh(&mut store);
        store
            .expect_machine_config_by_name()
            .once()
            .returning(|_| Ok(None));
        store
            .expect_add_machine_with_rootfs()
            .once()
            .returning(|config, state, rootfs| {
                assert_eq!(config.name, "devbox");
                assert_eq!(state.machine_id, config.id);
                assert_eq!(rootfs.machine_id, config.id);
                Ok(())
            });
        let runtime = runtime_with_mock_store(paths, store).await;

        let create = create_guard_sample(&runtime, "devbox")
            .await
            .expect("machine create guard should be created");
        let machine_dir = create.dir().to_path_buf();
        let config_path = create.dir().join("config.json");
        assert!(machine_dir.exists());
        assert!(config_path.exists());
        assert_eq!(
            std::fs::metadata(&machine_dir)
                .expect("machine directory metadata")
                .permissions()
                .mode()
                & 0o777,
            0o700
        );

        let rootfs = rootfs_record(&create);
        let config = create
            .commit(&runtime, rootfs, "test-image:latest".to_string(), Some(4))
            .await
            .expect("commit should succeed");

        assert!(config.machine_dir.exists());
        assert_eq!(config.machine_dir, machine_dir);
        assert!(config_path.exists());
    }

    #[tokio::test]
    async fn create_guard_drop_removes_machine_dir_and_frees_lock() {
        let temp = tempfile::tempdir().expect("tempdir");
        let paths = LocalPaths::new(temp.path().join("silo"));
        let mut store = MockDataStore::new();
        expect_empty_refresh(&mut store);
        store
            .expect_machine_config_by_name()
            .once()
            .returning(|_| Ok(None));
        let runtime = runtime_with_mock_store(paths, store).await;

        let create = create_guard_sample(&runtime, "devbox")
            .await
            .expect("machine create guard should be created");
        let machine_dir = create.dir().to_path_buf();
        let lock_id = create
            .lock
            .as_ref()
            .expect("create guard should hold lock")
            .id();
        let lock_path = runtime.local_paths().locks_dir().join(lock_id.to_string());
        assert!(machine_dir.exists());
        assert!(lock_path.exists());

        drop(create);

        assert!(!machine_dir.exists());
        assert!(!lock_path.exists());
    }

    #[tokio::test]
    async fn create_guard_commit_failure_removes_machine_dir_root_disk_and_frees_lock() {
        let temp = tempfile::tempdir().expect("tempdir");
        let paths = LocalPaths::new(temp.path().join("silo"));
        let mut store = MockDataStore::new();
        expect_empty_refresh(&mut store);
        store
            .expect_machine_config_by_name()
            .once()
            .returning(|_| Ok(None));
        store
            .expect_add_machine_with_rootfs()
            .once()
            .returning(|config, state, rootfs| {
                assert_eq!(config.name, "devbox");
                assert_eq!(state.machine_id, config.id);
                assert_eq!(rootfs.machine_id, config.id);
                Err(LibVmError::MachineAlreadyExists {
                    name: config.name.clone(),
                })
            });
        let runtime = runtime_with_mock_store(paths, store).await;

        let create = create_guard_sample(&runtime, "devbox")
            .await
            .expect("machine create guard should be created");
        let machine_dir = create.dir().to_path_buf();
        let root_disk_path = create.dir().join(root_disk_relative_path());
        let lock_id = create
            .lock
            .as_ref()
            .expect("create guard should hold lock")
            .id();
        let lock_path = runtime.local_paths().locks_dir().join(lock_id.to_string());
        std::fs::write(&root_disk_path, b"partial root disk").expect("write root disk");

        let rootfs = rootfs_record(&create);
        let err = create
            .commit(&runtime, rootfs, "test-image:latest".to_string(), Some(4))
            .await
            .expect_err("commit should fail");

        assert!(matches!(
            err,
            LibVmError::MachineAlreadyExists { ref name } if name == "devbox"
        ));
        assert!(!machine_dir.exists());
        assert!(!root_disk_path.exists());
        assert!(!lock_path.exists());
    }

    #[test]
    fn assign_mount_tags_fills_missing_tags_without_rewriting_sources() {
        let mounts = assign_mount_tags(vec![Mount {
            source: PathBuf::from("~"),
            tag: String::new(),
            read_only: false,
        }]);

        assert_eq!(mounts[0].source, PathBuf::from("~"));
        assert_eq!(mounts[0].tag, "mount0");
    }
}
