[package]
name = "vmmon"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "vmmon"
path = "src/main.rs"

[dependencies]
agent-spec = { path = "../../specs/agent-spec" }
base64 = "0.23.0"
chrono = "0.4.45"
virt = { path = "../../virt/virt" }
protocol = { path = "../../specs/protocol" }
vm-spec = { path = "../../specs/vm-spec" }
utils = { path = "../../common/utils" }
clap = { version = "4.6.4", features = ["derive"] }
eyre = "0.6.12"
futures = "0.3.33"
hyper-util = { version = "0.1.20", features = ["tokio"] }
libc = "0.2.189"
nix = { version = "0.31.3", features = ["signal", "fs", "socket", "process", "uio", "user"] }
bytes = "1.12.1"
prost-types = "0.14.4"
rand = "0.10.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["rt", "rt-multi-thread", "net", "io-util", "time", "signal", "sync", "fs", "process"] }
tokio-stream = { version = "0.1.19", features = ["net"] }
tokio-util = { version = "0.7.19", features = ["rt"] }
tonic = { version = "0.14.6", features = ["transport"] }
tonic-health = "0.14.6"
tonic-reflection = { version = "0.14.6", features = ["server"] }
tower = { version = "0.5.3", features = ["util"] }
thiserror = "2.0.19"
tracing = "0.1.44"
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3.23", features = ["fmt", "env-filter"] }
uuid = { version = "1.24.0", features = ["v4", "serde"] }
