FROM fedora:45

RUN dnf -y upgrade --refresh && \
    dnf -y install \
        vim \
        iptables \
        iproute \
        kmod \
        procps-ng \
        sudo \
        udev \
        systemd \
        openssh-server \
        e2fsprogs \
        tar && \
    dnf clean all && \
    rm -rf \
        /var/cache/dnf/* \
        /var/log/* \
        /tmp/* \
        /var/tmp/*

RUN systemctl enable \
    sshd.service \
    systemd-networkd.service \
    systemd-timesyncd.service \
    systemd-resolved.service

RUN printf 'L+ /etc/resolv.conf - - - - /run/systemd/resolve/stub-resolv.conf\n' > /etc/tmpfiles.d/resolv.conf \
  && (passwd -d root && passwd -u root || true) \
  && rm -f /etc/machine-id /var/lib/dbus/machine-id \
  && touch /etc/machine-id

# Configure SSHD
# RUN mkdir -p /var/empty/sshd # sshd needs this for some reason
