// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.31.1
// source: daemon.proto

package daemonv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DaemonService_GetStatus_FullMethodName             = "/silo.daemon.v1.DaemonService/GetStatus"
	DaemonService_GetRuntimeInfo_FullMethodName        = "/silo.daemon.v1.DaemonService/GetRuntimeInfo"
	DaemonService_ReportTailscaleStatus_FullMethodName = "/silo.daemon.v1.DaemonService/ReportTailscaleStatus"
	DaemonService_DrainMutations_FullMethodName        = "/silo.daemon.v1.DaemonService/DrainMutations"
)

// DaemonServiceClient is the client API for DaemonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DaemonServiceClient interface {
	GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DaemonStatus, error)
	GetRuntimeInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RuntimeInfo, error)
	ReportTailscaleStatus(ctx context.Context, in *TailscaleStatusReport, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DrainMutations(ctx context.Context, in *DrainMutationsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type daemonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonServiceClient(cc grpc.ClientConnInterface) DaemonServiceClient {
	return &daemonServiceClient{cc}
}

func (c *daemonServiceClient) GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DaemonStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DaemonStatus)
	err := c.cc.Invoke(ctx, DaemonService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetRuntimeInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RuntimeInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeInfo)
	err := c.cc.Invoke(ctx, DaemonService_GetRuntimeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ReportTailscaleStatus(ctx context.Context, in *TailscaleStatusReport, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DaemonService_ReportTailscaleStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) DrainMutations(ctx context.Context, in *DrainMutationsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DaemonService_DrainMutations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaemonServiceServer is the server API for DaemonService service.
// All implementations must embed UnimplementedDaemonServiceServer
// for forward compatibility.
type DaemonServiceServer interface {
	GetStatus(context.Context, *emptypb.Empty) (*DaemonStatus, error)
	GetRuntimeInfo(context.Context, *emptypb.Empty) (*RuntimeInfo, error)
	ReportTailscaleStatus(context.Context, *TailscaleStatusReport) (*emptypb.Empty, error)
	DrainMutations(context.Context, *DrainMutationsRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedDaemonServiceServer()
}

// UnimplementedDaemonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDaemonServiceServer struct{}

func (UnimplementedDaemonServiceServer) GetStatus(context.Context, *emptypb.Empty) (*DaemonStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedDaemonServiceServer) GetRuntimeInfo(context.Context, *emptypb.Empty) (*RuntimeInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRuntimeInfo not implemented")
}
func (UnimplementedDaemonServiceServer) ReportTailscaleStatus(context.Context, *TailscaleStatusReport) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportTailscaleStatus not implemented")
}
func (UnimplementedDaemonServiceServer) DrainMutations(context.Context, *DrainMutationsRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DrainMutations not implemented")
}
func (UnimplementedDaemonServiceServer) mustEmbedUnimplementedDaemonServiceServer() {}
func (UnimplementedDaemonServiceServer) testEmbeddedByValue()                       {}

// UnsafeDaemonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaemonServiceServer will
// result in compilation errors.
type UnsafeDaemonServiceServer interface {
	mustEmbedUnimplementedDaemonServiceServer()
}

func RegisterDaemonServiceServer(s grpc.ServiceRegistrar, srv DaemonServiceServer) {
	// If the following call panics, it indicates UnimplementedDaemonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DaemonService_ServiceDesc, srv)
}

func _DaemonService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetRuntimeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetRuntimeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetRuntimeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetRuntimeInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ReportTailscaleStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TailscaleStatusReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ReportTailscaleStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ReportTailscaleStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ReportTailscaleStatus(ctx, req.(*TailscaleStatusReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_DrainMutations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrainMutationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).DrainMutations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_DrainMutations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).DrainMutations(ctx, req.(*DrainMutationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DaemonService_ServiceDesc is the grpc.ServiceDesc for DaemonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DaemonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "silo.daemon.v1.DaemonService",
	HandlerType: (*DaemonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _DaemonService_GetStatus_Handler,
		},
		{
			MethodName: "GetRuntimeInfo",
			Handler:    _DaemonService_GetRuntimeInfo_Handler,
		},
		{
			MethodName: "ReportTailscaleStatus",
			Handler:    _DaemonService_ReportTailscaleStatus_Handler,
		},
		{
			MethodName: "DrainMutations",
			Handler:    _DaemonService_DrainMutations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "daemon.proto",
}

const (
	MachineService_ListMachines_FullMethodName        = "/silo.daemon.v1.MachineService/ListMachines"
	MachineService_InspectInventory_FullMethodName    = "/silo.daemon.v1.MachineService/InspectInventory"
	MachineService_InspectMachine_FullMethodName      = "/silo.daemon.v1.MachineService/InspectMachine"
	MachineService_EnsureNameAvailable_FullMethodName = "/silo.daemon.v1.MachineService/EnsureNameAvailable"
	MachineService_CreateMachine_FullMethodName       = "/silo.daemon.v1.MachineService/CreateMachine"
	MachineService_StartMachine_FullMethodName        = "/silo.daemon.v1.MachineService/StartMachine"
	MachineService_StopMachine_FullMethodName         = "/silo.daemon.v1.MachineService/StopMachine"
	MachineService_RemoveMachine_FullMethodName       = "/silo.daemon.v1.MachineService/RemoveMachine"
	MachineService_UpdateMachine_FullMethodName       = "/silo.daemon.v1.MachineService/UpdateMachine"
	MachineService_WaitReady_FullMethodName           = "/silo.daemon.v1.MachineService/WaitReady"
	MachineService_StopRun_FullMethodName             = "/silo.daemon.v1.MachineService/StopRun"
	MachineService_KillRun_FullMethodName             = "/silo.daemon.v1.MachineService/KillRun"
	MachineService_WaitForRun_FullMethodName          = "/silo.daemon.v1.MachineService/WaitForRun"
	MachineService_RemoveAfterRun_FullMethodName      = "/silo.daemon.v1.MachineService/RemoveAfterRun"
	MachineService_ReadLogs_FullMethodName            = "/silo.daemon.v1.MachineService/ReadLogs"
	MachineService_SetMachineSecret_FullMethodName    = "/silo.daemon.v1.MachineService/SetMachineSecret"
)

// MachineServiceClient is the client API for MachineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MachineServiceClient interface {
	ListMachines(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MachineInventoryEntry], error)
	InspectInventory(ctx context.Context, in *MachineRef, opts ...grpc.CallOption) (*MachineInventoryEntry, error)
	InspectMachine(ctx context.Context, in *MachineRef, opts ...grpc.CallOption) (*MachineSnapshot, error)
	EnsureNameAvailable(ctx context.Context, in *Name, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreateMachine(ctx context.Context, in *CreateMachineRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CreateMachineEvent], error)
	StartMachine(ctx context.Context, in *StartMachineRequest, opts ...grpc.CallOption) (*MachineStart, error)
	StopMachine(ctx context.Context, in *StopMachineRequest, opts ...grpc.CallOption) (*MachineSnapshot, error)
	RemoveMachine(ctx context.Context, in *RemoveMachineRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateMachine(ctx context.Context, in *UpdateMachineRequest, opts ...grpc.CallOption) (*MachineSnapshot, error)
	WaitReady(ctx context.Context, in *WaitReadyRequest, opts ...grpc.CallOption) (*MachineReadiness, error)
	StopRun(ctx context.Context, in *StopRunRequest, opts ...grpc.CallOption) (*MachineSnapshot, error)
	KillRun(ctx context.Context, in *KillRunRequest, opts ...grpc.CallOption) (*MachineExit, error)
	WaitForRun(ctx context.Context, in *WaitForRunRequest, opts ...grpc.CallOption) (*MachineExit, error)
	RemoveAfterRun(ctx context.Context, in *MachineRunRef, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReadLogs(ctx context.Context, in *ReadLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error)
	SetMachineSecret(ctx context.Context, in *SetMachineSecretRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type machineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMachineServiceClient(cc grpc.ClientConnInterface) MachineServiceClient {
	return &machineServiceClient{cc}
}

func (c *machineServiceClient) ListMachines(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MachineInventoryEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MachineService_ServiceDesc.Streams[0], MachineService_ListMachines_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, MachineInventoryEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MachineService_ListMachinesClient = grpc.ServerStreamingClient[MachineInventoryEntry]

func (c *machineServiceClient) InspectInventory(ctx context.Context, in *MachineRef, opts ...grpc.CallOption) (*MachineInventoryEntry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MachineInventoryEntry)
	err := c.cc.Invoke(ctx, MachineService_InspectInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineServiceClient) InspectMachine(ctx context.Context, in *MachineRef, opts ...grpc.CallOption) (*MachineSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MachineSnapshot)
	err := c.cc.Invoke(ctx, MachineService_InspectMachine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineServiceClient) EnsureNameAvailable(ctx context.Context, in *Name, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MachineService_EnsureNameAvailable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineServiceClient) CreateMachine(ctx context.Context, in *CreateMachineRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CreateMachineEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MachineService_ServiceDesc.Streams[1], MachineService_CreateMachine_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CreateMachineRequest, CreateMachineEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MachineService_CreateMachineClient = grpc.ServerStreamingClient[CreateMachineEvent]

func (c *machineServiceClient) StartMachine(ctx context.Context, in *StartMachineRequest, opts ...grpc.CallOption) (*MachineStart, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MachineStart)
	err := c.cc.Invoke(ctx, MachineService_StartMachine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineServiceClient) StopMachine(ctx context.Context, in *StopMachineRequest, opts ...grpc.CallOption) (*MachineSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MachineSnapshot)
	err := c.cc.Invoke(ctx, MachineService_StopMachine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineServiceClient) RemoveMachine(ctx context.Context, in *RemoveMachineRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MachineService_RemoveMachine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineServiceClient) UpdateMachine(ctx context.Context, in *UpdateMachineRequest, opts ...grpc.CallOption) (*MachineSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MachineSnapshot)
	err := c.cc.Invoke(ctx, MachineService_UpdateMachine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineServiceClient) WaitReady(ctx context.Context, in *WaitReadyRequest, opts ...grpc.CallOption) (*MachineReadiness, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MachineReadiness)
	err := c.cc.Invoke(ctx, MachineService_WaitReady_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineServiceClient) StopRun(ctx context.Context, in *StopRunRequest, opts ...grpc.CallOption) (*MachineSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MachineSnapshot)
	err := c.cc.Invoke(ctx, MachineService_StopRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineServiceClient) KillRun(ctx context.Context, in *KillRunRequest, opts ...grpc.CallOption) (*MachineExit, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MachineExit)
	err := c.cc.Invoke(ctx, MachineService_KillRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineServiceClient) WaitForRun(ctx context.Context, in *WaitForRunRequest, opts ...grpc.CallOption) (*MachineExit, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MachineExit)
	err := c.cc.Invoke(ctx, MachineService_WaitForRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineServiceClient) RemoveAfterRun(ctx context.Context, in *MachineRunRef, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MachineService_RemoveAfterRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineServiceClient) ReadLogs(ctx context.Context, in *ReadLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MachineService_ServiceDesc.Streams[2], MachineService_ReadLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadLogsRequest, LogChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MachineService_ReadLogsClient = grpc.ServerStreamingClient[LogChunk]

func (c *machineServiceClient) SetMachineSecret(ctx context.Context, in *SetMachineSecretRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MachineService_SetMachineSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MachineServiceServer is the server API for MachineService service.
// All implementations must embed UnimplementedMachineServiceServer
// for forward compatibility.
type MachineServiceServer interface {
	ListMachines(*emptypb.Empty, grpc.ServerStreamingServer[MachineInventoryEntry]) error
	InspectInventory(context.Context, *MachineRef) (*MachineInventoryEntry, error)
	InspectMachine(context.Context, *MachineRef) (*MachineSnapshot, error)
	EnsureNameAvailable(context.Context, *Name) (*emptypb.Empty, error)
	CreateMachine(*CreateMachineRequest, grpc.ServerStreamingServer[CreateMachineEvent]) error
	StartMachine(context.Context, *StartMachineRequest) (*MachineStart, error)
	StopMachine(context.Context, *StopMachineRequest) (*MachineSnapshot, error)
	RemoveMachine(context.Context, *RemoveMachineRequest) (*emptypb.Empty, error)
	UpdateMachine(context.Context, *UpdateMachineRequest) (*MachineSnapshot, error)
	WaitReady(context.Context, *WaitReadyRequest) (*MachineReadiness, error)
	StopRun(context.Context, *StopRunRequest) (*MachineSnapshot, error)
	KillRun(context.Context, *KillRunRequest) (*MachineExit, error)
	WaitForRun(context.Context, *WaitForRunRequest) (*MachineExit, error)
	RemoveAfterRun(context.Context, *MachineRunRef) (*emptypb.Empty, error)
	ReadLogs(*ReadLogsRequest, grpc.ServerStreamingServer[LogChunk]) error
	SetMachineSecret(context.Context, *SetMachineSecretRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedMachineServiceServer()
}

// UnimplementedMachineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMachineServiceServer struct{}

func (UnimplementedMachineServiceServer) ListMachines(*emptypb.Empty, grpc.ServerStreamingServer[MachineInventoryEntry]) error {
	return status.Error(codes.Unimplemented, "method ListMachines not implemented")
}
func (UnimplementedMachineServiceServer) InspectInventory(context.Context, *MachineRef) (*MachineInventoryEntry, error) {
	return nil, status.Error(codes.Unimplemented, "method InspectInventory not implemented")
}
func (UnimplementedMachineServiceServer) InspectMachine(context.Context, *MachineRef) (*MachineSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method InspectMachine not implemented")
}
func (UnimplementedMachineServiceServer) EnsureNameAvailable(context.Context, *Name) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsureNameAvailable not implemented")
}
func (UnimplementedMachineServiceServer) CreateMachine(*CreateMachineRequest, grpc.ServerStreamingServer[CreateMachineEvent]) error {
	return status.Error(codes.Unimplemented, "method CreateMachine not implemented")
}
func (UnimplementedMachineServiceServer) StartMachine(context.Context, *StartMachineRequest) (*MachineStart, error) {
	return nil, status.Error(codes.Unimplemented, "method StartMachine not implemented")
}
func (UnimplementedMachineServiceServer) StopMachine(context.Context, *StopMachineRequest) (*MachineSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method StopMachine not implemented")
}
func (UnimplementedMachineServiceServer) RemoveMachine(context.Context, *RemoveMachineRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMachine not implemented")
}
func (UnimplementedMachineServiceServer) UpdateMachine(context.Context, *UpdateMachineRequest) (*MachineSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMachine not implemented")
}
func (UnimplementedMachineServiceServer) WaitReady(context.Context, *WaitReadyRequest) (*MachineReadiness, error) {
	return nil, status.Error(codes.Unimplemented, "method WaitReady not implemented")
}
func (UnimplementedMachineServiceServer) StopRun(context.Context, *StopRunRequest) (*MachineSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method StopRun not implemented")
}
func (UnimplementedMachineServiceServer) KillRun(context.Context, *KillRunRequest) (*MachineExit, error) {
	return nil, status.Error(codes.Unimplemented, "method KillRun not implemented")
}
func (UnimplementedMachineServiceServer) WaitForRun(context.Context, *WaitForRunRequest) (*MachineExit, error) {
	return nil, status.Error(codes.Unimplemented, "method WaitForRun not implemented")
}
func (UnimplementedMachineServiceServer) RemoveAfterRun(context.Context, *MachineRunRef) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveAfterRun not implemented")
}
func (UnimplementedMachineServiceServer) ReadLogs(*ReadLogsRequest, grpc.ServerStreamingServer[LogChunk]) error {
	return status.Error(codes.Unimplemented, "method ReadLogs not implemented")
}
func (UnimplementedMachineServiceServer) SetMachineSecret(context.Context, *SetMachineSecretRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMachineSecret not implemented")
}
func (UnimplementedMachineServiceServer) mustEmbedUnimplementedMachineServiceServer() {}
func (UnimplementedMachineServiceServer) testEmbeddedByValue()                        {}

// UnsafeMachineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MachineServiceServer will
// result in compilation errors.
type UnsafeMachineServiceServer interface {
	mustEmbedUnimplementedMachineServiceServer()
}

func RegisterMachineServiceServer(s grpc.ServiceRegistrar, srv MachineServiceServer) {
	// If the following call panics, it indicates UnimplementedMachineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MachineService_ServiceDesc, srv)
}

func _MachineService_ListMachines_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MachineServiceServer).ListMachines(m, &grpc.GenericServerStream[emptypb.Empty, MachineInventoryEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MachineService_ListMachinesServer = grpc.ServerStreamingServer[MachineInventoryEntry]

func _MachineService_InspectInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MachineRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineServiceServer).InspectInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineService_InspectInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineServiceServer).InspectInventory(ctx, req.(*MachineRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineService_InspectMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MachineRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineServiceServer).InspectMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineService_InspectMachine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineServiceServer).InspectMachine(ctx, req.(*MachineRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineService_EnsureNameAvailable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineServiceServer).EnsureNameAvailable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineService_EnsureNameAvailable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineServiceServer).EnsureNameAvailable(ctx, req.(*Name))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineService_CreateMachine_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CreateMachineRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MachineServiceServer).CreateMachine(m, &grpc.GenericServerStream[CreateMachineRequest, CreateMachineEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MachineService_CreateMachineServer = grpc.ServerStreamingServer[CreateMachineEvent]

func _MachineService_StartMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineServiceServer).StartMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineService_StartMachine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineServiceServer).StartMachine(ctx, req.(*StartMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineService_StopMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineServiceServer).StopMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineService_StopMachine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineServiceServer).StopMachine(ctx, req.(*StopMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineService_RemoveMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineServiceServer).RemoveMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineService_RemoveMachine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineServiceServer).RemoveMachine(ctx, req.(*RemoveMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineService_UpdateMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineServiceServer).UpdateMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineService_UpdateMachine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineServiceServer).UpdateMachine(ctx, req.(*UpdateMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineService_WaitReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineServiceServer).WaitReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineService_WaitReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineServiceServer).WaitReady(ctx, req.(*WaitReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineService_StopRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineServiceServer).StopRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineService_StopRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineServiceServer).StopRun(ctx, req.(*StopRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineService_KillRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineServiceServer).KillRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineService_KillRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineServiceServer).KillRun(ctx, req.(*KillRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineService_WaitForRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitForRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineServiceServer).WaitForRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineService_WaitForRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineServiceServer).WaitForRun(ctx, req.(*WaitForRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineService_RemoveAfterRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MachineRunRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineServiceServer).RemoveAfterRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineService_RemoveAfterRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineServiceServer).RemoveAfterRun(ctx, req.(*MachineRunRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineService_ReadLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MachineServiceServer).ReadLogs(m, &grpc.GenericServerStream[ReadLogsRequest, LogChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MachineService_ReadLogsServer = grpc.ServerStreamingServer[LogChunk]

func _MachineService_SetMachineSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMachineSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineServiceServer).SetMachineSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineService_SetMachineSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineServiceServer).SetMachineSecret(ctx, req.(*SetMachineSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MachineService_ServiceDesc is the grpc.ServiceDesc for MachineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MachineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "silo.daemon.v1.MachineService",
	HandlerType: (*MachineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InspectInventory",
			Handler:    _MachineService_InspectInventory_Handler,
		},
		{
			MethodName: "InspectMachine",
			Handler:    _MachineService_InspectMachine_Handler,
		},
		{
			MethodName: "EnsureNameAvailable",
			Handler:    _MachineService_EnsureNameAvailable_Handler,
		},
		{
			MethodName: "StartMachine",
			Handler:    _MachineService_StartMachine_Handler,
		},
		{
			MethodName: "StopMachine",
			Handler:    _MachineService_StopMachine_Handler,
		},
		{
			MethodName: "RemoveMachine",
			Handler:    _MachineService_RemoveMachine_Handler,
		},
		{
			MethodName: "UpdateMachine",
			Handler:    _MachineService_UpdateMachine_Handler,
		},
		{
			MethodName: "WaitReady",
			Handler:    _MachineService_WaitReady_Handler,
		},
		{
			MethodName: "StopRun",
			Handler:    _MachineService_StopRun_Handler,
		},
		{
			MethodName: "KillRun",
			Handler:    _MachineService_KillRun_Handler,
		},
		{
			MethodName: "WaitForRun",
			Handler:    _MachineService_WaitForRun_Handler,
		},
		{
			MethodName: "RemoveAfterRun",
			Handler:    _MachineService_RemoveAfterRun_Handler,
		},
		{
			MethodName: "SetMachineSecret",
			Handler:    _MachineService_SetMachineSecret_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListMachines",
			Handler:       _MachineService_ListMachines_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CreateMachine",
			Handler:       _MachineService_CreateMachine_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReadLogs",
			Handler:       _MachineService_ReadLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "daemon.proto",
}

const (
	NetworkService_ListNetworkDefinitions_FullMethodName  = "/silo.daemon.v1.NetworkService/ListNetworkDefinitions"
	NetworkService_GetNetworkDefinition_FullMethodName    = "/silo.daemon.v1.NetworkService/GetNetworkDefinition"
	NetworkService_CreateNetworkDefinition_FullMethodName = "/silo.daemon.v1.NetworkService/CreateNetworkDefinition"
	NetworkService_RemoveNetworkDefinition_FullMethodName = "/silo.daemon.v1.NetworkService/RemoveNetworkDefinition"
	NetworkService_SetMachineNetwork_FullMethodName       = "/silo.daemon.v1.NetworkService/SetMachineNetwork"
)

// NetworkServiceClient is the client API for NetworkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetworkServiceClient interface {
	ListNetworkDefinitions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NetworkDefinition], error)
	GetNetworkDefinition(ctx context.Context, in *Name, opts ...grpc.CallOption) (*OptionalNetworkDefinition, error)
	CreateNetworkDefinition(ctx context.Context, in *CreateNetworkDefinitionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveNetworkDefinition(ctx context.Context, in *Name, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SetMachineNetwork(ctx context.Context, in *SetMachineNetworkRequest, opts ...grpc.CallOption) (*MachineSnapshot, error)
}

type networkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkServiceClient(cc grpc.ClientConnInterface) NetworkServiceClient {
	return &networkServiceClient{cc}
}

func (c *networkServiceClient) ListNetworkDefinitions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NetworkDefinition], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NetworkService_ServiceDesc.Streams[0], NetworkService_ListNetworkDefinitions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, NetworkDefinition]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetworkService_ListNetworkDefinitionsClient = grpc.ServerStreamingClient[NetworkDefinition]

func (c *networkServiceClient) GetNetworkDefinition(ctx context.Context, in *Name, opts ...grpc.CallOption) (*OptionalNetworkDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OptionalNetworkDefinition)
	err := c.cc.Invoke(ctx, NetworkService_GetNetworkDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceClient) CreateNetworkDefinition(ctx context.Context, in *CreateNetworkDefinitionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NetworkService_CreateNetworkDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceClient) RemoveNetworkDefinition(ctx context.Context, in *Name, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NetworkService_RemoveNetworkDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceClient) SetMachineNetwork(ctx context.Context, in *SetMachineNetworkRequest, opts ...grpc.CallOption) (*MachineSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MachineSnapshot)
	err := c.cc.Invoke(ctx, NetworkService_SetMachineNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkServiceServer is the server API for NetworkService service.
// All implementations must embed UnimplementedNetworkServiceServer
// for forward compatibility.
type NetworkServiceServer interface {
	ListNetworkDefinitions(*emptypb.Empty, grpc.ServerStreamingServer[NetworkDefinition]) error
	GetNetworkDefinition(context.Context, *Name) (*OptionalNetworkDefinition, error)
	CreateNetworkDefinition(context.Context, *CreateNetworkDefinitionRequest) (*emptypb.Empty, error)
	RemoveNetworkDefinition(context.Context, *Name) (*emptypb.Empty, error)
	SetMachineNetwork(context.Context, *SetMachineNetworkRequest) (*MachineSnapshot, error)
	mustEmbedUnimplementedNetworkServiceServer()
}

// UnimplementedNetworkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetworkServiceServer struct{}

func (UnimplementedNetworkServiceServer) ListNetworkDefinitions(*emptypb.Empty, grpc.ServerStreamingServer[NetworkDefinition]) error {
	return status.Error(codes.Unimplemented, "method ListNetworkDefinitions not implemented")
}
func (UnimplementedNetworkServiceServer) GetNetworkDefinition(context.Context, *Name) (*OptionalNetworkDefinition, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNetworkDefinition not implemented")
}
func (UnimplementedNetworkServiceServer) CreateNetworkDefinition(context.Context, *CreateNetworkDefinitionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNetworkDefinition not implemented")
}
func (UnimplementedNetworkServiceServer) RemoveNetworkDefinition(context.Context, *Name) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveNetworkDefinition not implemented")
}
func (UnimplementedNetworkServiceServer) SetMachineNetwork(context.Context, *SetMachineNetworkRequest) (*MachineSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMachineNetwork not implemented")
}
func (UnimplementedNetworkServiceServer) mustEmbedUnimplementedNetworkServiceServer() {}
func (UnimplementedNetworkServiceServer) testEmbeddedByValue()                        {}

// UnsafeNetworkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkServiceServer will
// result in compilation errors.
type UnsafeNetworkServiceServer interface {
	mustEmbedUnimplementedNetworkServiceServer()
}

func RegisterNetworkServiceServer(s grpc.ServiceRegistrar, srv NetworkServiceServer) {
	// If the following call panics, it indicates UnimplementedNetworkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetworkService_ServiceDesc, srv)
}

func _NetworkService_ListNetworkDefinitions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NetworkServiceServer).ListNetworkDefinitions(m, &grpc.GenericServerStream[emptypb.Empty, NetworkDefinition]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetworkService_ListNetworkDefinitionsServer = grpc.ServerStreamingServer[NetworkDefinition]

func _NetworkService_GetNetworkDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).GetNetworkDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkService_GetNetworkDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).GetNetworkDefinition(ctx, req.(*Name))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkService_CreateNetworkDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNetworkDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).CreateNetworkDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkService_CreateNetworkDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).CreateNetworkDefinition(ctx, req.(*CreateNetworkDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkService_RemoveNetworkDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).RemoveNetworkDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkService_RemoveNetworkDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).RemoveNetworkDefinition(ctx, req.(*Name))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkService_SetMachineNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMachineNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).SetMachineNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkService_SetMachineNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).SetMachineNetwork(ctx, req.(*SetMachineNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NetworkService_ServiceDesc is the grpc.ServiceDesc for NetworkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetworkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "silo.daemon.v1.NetworkService",
	HandlerType: (*NetworkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNetworkDefinition",
			Handler:    _NetworkService_GetNetworkDefinition_Handler,
		},
		{
			MethodName: "CreateNetworkDefinition",
			Handler:    _NetworkService_CreateNetworkDefinition_Handler,
		},
		{
			MethodName: "RemoveNetworkDefinition",
			Handler:    _NetworkService_RemoveNetworkDefinition_Handler,
		},
		{
			MethodName: "SetMachineNetwork",
			Handler:    _NetworkService_SetMachineNetwork_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListNetworkDefinitions",
			Handler:       _NetworkService_ListNetworkDefinitions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "daemon.proto",
}

const (
	RuntimeService_ResolveImage_FullMethodName       = "/silo.daemon.v1.RuntimeService/ResolveImage"
	RuntimeService_PullImage_FullMethodName          = "/silo.daemon.v1.RuntimeService/PullImage"
	RuntimeService_ProposeMachineName_FullMethodName = "/silo.daemon.v1.RuntimeService/ProposeMachineName"
	RuntimeService_ParseResource_FullMethodName      = "/silo.daemon.v1.RuntimeService/ParseResource"
	RuntimeService_NormalizePolicy_FullMethodName    = "/silo.daemon.v1.RuntimeService/NormalizePolicy"
	RuntimeService_CheckPolicySecrets_FullMethodName = "/silo.daemon.v1.RuntimeService/CheckPolicySecrets"
)

// RuntimeServiceClient is the client API for RuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RuntimeServiceClient interface {
	ResolveImage(ctx context.Context, in *ResolveImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResolveImageEvent], error)
	PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ImageProgress], error)
	ProposeMachineName(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Name, error)
	ParseResource(ctx context.Context, in *ParseResourceRequest, opts ...grpc.CallOption) (*Size, error)
	NormalizePolicy(ctx context.Context, in *NormalizePolicyRequest, opts ...grpc.CallOption) (*PolicyDocument, error)
	CheckPolicySecrets(ctx context.Context, in *CheckPolicySecretsRequest, opts ...grpc.CallOption) (*PolicySecretsResult, error)
}

type runtimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeServiceClient(cc grpc.ClientConnInterface) RuntimeServiceClient {
	return &runtimeServiceClient{cc}
}

func (c *runtimeServiceClient) ResolveImage(ctx context.Context, in *ResolveImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResolveImageEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RuntimeService_ServiceDesc.Streams[0], RuntimeService_ResolveImage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ResolveImageRequest, ResolveImageEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeService_ResolveImageClient = grpc.ServerStreamingClient[ResolveImageEvent]

func (c *runtimeServiceClient) PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ImageProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RuntimeService_ServiceDesc.Streams[1], RuntimeService_PullImage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PullImageRequest, ImageProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeService_PullImageClient = grpc.ServerStreamingClient[ImageProgress]

func (c *runtimeServiceClient) ProposeMachineName(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Name, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Name)
	err := c.cc.Invoke(ctx, RuntimeService_ProposeMachineName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) ParseResource(ctx context.Context, in *ParseResourceRequest, opts ...grpc.CallOption) (*Size, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Size)
	err := c.cc.Invoke(ctx, RuntimeService_ParseResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) NormalizePolicy(ctx context.Context, in *NormalizePolicyRequest, opts ...grpc.CallOption) (*PolicyDocument, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolicyDocument)
	err := c.cc.Invoke(ctx, RuntimeService_NormalizePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) CheckPolicySecrets(ctx context.Context, in *CheckPolicySecretsRequest, opts ...grpc.CallOption) (*PolicySecretsResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolicySecretsResult)
	err := c.cc.Invoke(ctx, RuntimeService_CheckPolicySecrets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuntimeServiceServer is the server API for RuntimeService service.
// All implementations must embed UnimplementedRuntimeServiceServer
// for forward compatibility.
type RuntimeServiceServer interface {
	ResolveImage(*ResolveImageRequest, grpc.ServerStreamingServer[ResolveImageEvent]) error
	PullImage(*PullImageRequest, grpc.ServerStreamingServer[ImageProgress]) error
	ProposeMachineName(context.Context, *emptypb.Empty) (*Name, error)
	ParseResource(context.Context, *ParseResourceRequest) (*Size, error)
	NormalizePolicy(context.Context, *NormalizePolicyRequest) (*PolicyDocument, error)
	CheckPolicySecrets(context.Context, *CheckPolicySecretsRequest) (*PolicySecretsResult, error)
	mustEmbedUnimplementedRuntimeServiceServer()
}

// UnimplementedRuntimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuntimeServiceServer struct{}

func (UnimplementedRuntimeServiceServer) ResolveImage(*ResolveImageRequest, grpc.ServerStreamingServer[ResolveImageEvent]) error {
	return status.Error(codes.Unimplemented, "method ResolveImage not implemented")
}
func (UnimplementedRuntimeServiceServer) PullImage(*PullImageRequest, grpc.ServerStreamingServer[ImageProgress]) error {
	return status.Error(codes.Unimplemented, "method PullImage not implemented")
}
func (UnimplementedRuntimeServiceServer) ProposeMachineName(context.Context, *emptypb.Empty) (*Name, error) {
	return nil, status.Error(codes.Unimplemented, "method ProposeMachineName not implemented")
}
func (UnimplementedRuntimeServiceServer) ParseResource(context.Context, *ParseResourceRequest) (*Size, error) {
	return nil, status.Error(codes.Unimplemented, "method ParseResource not implemented")
}
func (UnimplementedRuntimeServiceServer) NormalizePolicy(context.Context, *NormalizePolicyRequest) (*PolicyDocument, error) {
	return nil, status.Error(codes.Unimplemented, "method NormalizePolicy not implemented")
}
func (UnimplementedRuntimeServiceServer) CheckPolicySecrets(context.Context, *CheckPolicySecretsRequest) (*PolicySecretsResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckPolicySecrets not implemented")
}
func (UnimplementedRuntimeServiceServer) mustEmbedUnimplementedRuntimeServiceServer() {}
func (UnimplementedRuntimeServiceServer) testEmbeddedByValue()                        {}

// UnsafeRuntimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuntimeServiceServer will
// result in compilation errors.
type UnsafeRuntimeServiceServer interface {
	mustEmbedUnimplementedRuntimeServiceServer()
}

func RegisterRuntimeServiceServer(s grpc.ServiceRegistrar, srv RuntimeServiceServer) {
	// If the following call panics, it indicates UnimplementedRuntimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RuntimeService_ServiceDesc, srv)
}

func _RuntimeService_ResolveImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ResolveImageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuntimeServiceServer).ResolveImage(m, &grpc.GenericServerStream[ResolveImageRequest, ResolveImageEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeService_ResolveImageServer = grpc.ServerStreamingServer[ResolveImageEvent]

func _RuntimeService_PullImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullImageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuntimeServiceServer).PullImage(m, &grpc.GenericServerStream[PullImageRequest, ImageProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeService_PullImageServer = grpc.ServerStreamingServer[ImageProgress]

func _RuntimeService_ProposeMachineName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).ProposeMachineName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_ProposeMachineName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).ProposeMachineName(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_ParseResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).ParseResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_ParseResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).ParseResource(ctx, req.(*ParseResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_NormalizePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NormalizePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).NormalizePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_NormalizePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).NormalizePolicy(ctx, req.(*NormalizePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_CheckPolicySecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPolicySecretsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).CheckPolicySecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_CheckPolicySecrets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).CheckPolicySecrets(ctx, req.(*CheckPolicySecretsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RuntimeService_ServiceDesc is the grpc.ServiceDesc for RuntimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuntimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "silo.daemon.v1.RuntimeService",
	HandlerType: (*RuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProposeMachineName",
			Handler:    _RuntimeService_ProposeMachineName_Handler,
		},
		{
			MethodName: "ParseResource",
			Handler:    _RuntimeService_ParseResource_Handler,
		},
		{
			MethodName: "NormalizePolicy",
			Handler:    _RuntimeService_NormalizePolicy_Handler,
		},
		{
			MethodName: "CheckPolicySecrets",
			Handler:    _RuntimeService_CheckPolicySecrets_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ResolveImage",
			Handler:       _RuntimeService_ResolveImage_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PullImage",
			Handler:       _RuntimeService_PullImage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "daemon.proto",
}
