FROM ubuntu:24.04

RUN apt update && \
    apt upgrade -y && \
    apt install -y \
        vim \
        iptables \
        iproute2 \
        kmod \
        procps \
        sudo \
        udev \
        systemd \
        openssh-server \
        e2fsprogs \
        tar && \
    apt clean && \
    rm -rf \
        /var/cache/apt/* \
        /var/log/* \
        /tmp/* \
        /var/tmp/*

RUN systemctl enable \
    systemd-timesyncd.service

RUN (passwd -d root && passwd -u root || true) \
  && rm -f /etc/machine-id /var/lib/dbus/machine-id \
  && touch /etc/machine-id
