use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex, PoisonError};

use crate::virt::error::VirtError;

/// Opaque, persistable machine identity.
///
/// Backends that mint hardware identities (Virtualization.framework's generic
/// machine identifier) write generated bytes back through this handle so the
/// caller can persist them across runs: check [`MachineIdentifier::was_generated`]
/// after machine construction and store [`MachineIdentifier::bytes`] if set.
#[derive(Debug, Clone, Default)]
pub struct MachineIdentifier {
    inner: Arc<Mutex<MachineIdentifierState>>,
}

#[derive(Debug, Default)]
struct MachineIdentifierState {
    bytes: Vec<u8>,
    generated: bool,
}

impl MachineIdentifier {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn from_bytes(bytes: Vec<u8>) -> Self {
        Self {
            inner: Arc::new(Mutex::new(MachineIdentifierState {
                bytes,
                generated: false,
            })),
        }
    }

    pub fn bytes(&self) -> Vec<u8> {
        self.lock().bytes.clone()
    }

    pub fn is_empty(&self) -> bool {
        self.lock().bytes.is_empty()
    }

    /// True when a backend generated a fresh identity during machine
    /// construction; the caller should persist [`MachineIdentifier::bytes`].
    pub fn was_generated(&self) -> bool {
        self.lock().generated
    }

    pub(crate) fn set_generated_bytes(&self, bytes: Vec<u8>) {
        let mut state = self.lock();
        state.bytes = bytes;
        state.generated = true;
    }

    fn lock(&self) -> std::sync::MutexGuard<'_, MachineIdentifierState> {
        self.inner.lock().unwrap_or_else(PoisonError::into_inner)
    }
}

impl PartialEq for MachineIdentifier {
    fn eq(&self, other: &Self) -> bool {
        self.bytes() == other.bytes()
    }
}

impl Eq for MachineIdentifier {}

/// A block device attached to the guest.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DiskImage {
    pub path: PathBuf,
    pub read_only: bool,
}

/// A host directory exposed to the guest as a virtiofs share.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SharedDirectory {
    pub host_path: PathBuf,
    pub tag: String,
    pub read_only: bool,
}

/// Guest network attachment.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
#[non_exhaustive]
pub enum NetworkMode {
    #[default]
    None,
    UnixDatagram {
        peer_path: PathBuf,
        mac: [u8; 6],
    },
}

/// Options consumed only by the krun (Linux) backend; other backends ignore them.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct KrunOptions {
    /// Per-start compatibility data acquired and released before helper spawn.
    pub prepared_rosetta: Option<crate::krun::RosettaLaunchConfig>,
}

/// Backend-specific realization of a machine's transient Rosetta intent.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum RosettaIntent {
    #[default]
    Disabled,
    VzNative,
    KrunCaptured {
        profile: RosettaProfile,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RosettaProfile {
    CapturedCompatibilityV1,
}

/// Options consumed only by the Virtualization.framework (macOS) backend.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct VzOptions {
    /// Persisted machine identity; generated on first boot and written back.
    pub machine_identifier: Option<MachineIdentifier>,
}

/// Options consumed only by the mock backend (compiled with the
/// `mock-backend` feature); other backends ignore them.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct MockOptions {
    /// Absolute path to a scenario file scripting the mock's behavior.
    /// Absent means the happy-path default scenario.
    pub scenario: Option<PathBuf>,
}

/// Declarative description of a machine, independent of any backend.
///
/// Construct with [`VmConfig::builder`]. Building never fails; each backend
/// validates the configuration it is given when the machine is created.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct VmConfig {
    name: String,
    vm_id: String,
    base_directory: PathBuf,
    cpus: Option<usize>,
    memory_mib: Option<u64>,
    kernel_path: Option<PathBuf>,
    initramfs_path: Option<PathBuf>,
    kernel_cmdline: Vec<String>,
    nested_virtualization: bool,
    network: NetworkMode,
    disks: Vec<DiskImage>,
    mounts: Vec<SharedDirectory>,
    rosetta: RosettaIntent,
    krun: KrunOptions,
    vz: VzOptions,
    mock: MockOptions,
}

impl VmConfig {
    pub fn builder(name: impl Into<String>) -> VmConfigBuilder {
        VmConfigBuilder {
            config: VmConfig {
                name: name.into(),
                ..VmConfig::default()
            },
        }
    }

    pub fn name(&self) -> &str {
        &self.name
    }

    pub fn vm_id(&self) -> &str {
        &self.vm_id
    }

    pub fn base_directory(&self) -> &Path {
        &self.base_directory
    }

    pub fn cpus(&self) -> Option<usize> {
        self.cpus
    }

    pub fn memory_mib(&self) -> Option<u64> {
        self.memory_mib
    }

    pub fn kernel_path(&self) -> Option<&Path> {
        self.kernel_path.as_deref()
    }

    pub fn initramfs_path(&self) -> Option<&Path> {
        self.initramfs_path.as_deref()
    }

    pub fn kernel_cmdline(&self) -> &[String] {
        &self.kernel_cmdline
    }

    pub fn nested_virtualization(&self) -> bool {
        self.nested_virtualization
    }

    pub fn network(&self) -> &NetworkMode {
        &self.network
    }

    pub fn disks(&self) -> &[DiskImage] {
        &self.disks
    }

    pub fn mounts(&self) -> &[SharedDirectory] {
        &self.mounts
    }

    pub fn rosetta(&self) -> RosettaIntent {
        self.rosetta
    }

    pub fn krun(&self) -> &KrunOptions {
        &self.krun
    }

    pub fn vz(&self) -> &VzOptions {
        &self.vz
    }

    #[cfg(feature = "mock-backend")]
    pub fn mock(&self) -> &MockOptions {
        &self.mock
    }

    /// Set the mock scenario path on an already-built config (used when the
    /// start request selects the mock backend after spec resolution).
    #[cfg(feature = "mock-backend")]
    pub fn set_mock_scenario(&mut self, path: impl Into<PathBuf>) {
        self.mock.scenario = Some(path.into());
    }

    #[cfg(test)]
    pub fn unix_datagram_network(&self) -> Option<(&PathBuf, [u8; 6])> {
        match &self.network {
            NetworkMode::UnixDatagram { peer_path, mac } => Some((peer_path, *mac)),
            _ => None,
        }
    }
}

/// Builder for [`VmConfig`]. All methods are chainable; `build` is infallible.
#[derive(Debug, Clone)]
pub struct VmConfigBuilder {
    config: VmConfig,
}

impl VmConfigBuilder {
    pub fn vm_id(mut self, vm_id: impl Into<String>) -> Self {
        self.config.vm_id = vm_id.into();
        self
    }

    pub fn base_directory(mut self, path: impl Into<PathBuf>) -> Self {
        self.config.base_directory = path.into();
        self
    }

    pub fn cpus(mut self, cpus: usize) -> Self {
        self.config.cpus = Some(cpus);
        self
    }

    pub fn memory(mut self, memory_mib: u64) -> Self {
        self.config.memory_mib = Some(memory_mib);
        self
    }

    pub fn kernel(mut self, path: impl Into<PathBuf>) -> Self {
        self.config.kernel_path = Some(path.into());
        self
    }

    pub fn initramfs(mut self, path: impl Into<PathBuf>) -> Self {
        self.config.initramfs_path = Some(path.into());
        self
    }

    pub fn kernel_cmdline(mut self, kernel_cmdline: Vec<String>) -> Self {
        self.config.kernel_cmdline = kernel_cmdline;
        self
    }

    pub fn nested_virtualization(mut self, enabled: bool) -> Self {
        self.config.nested_virtualization = enabled;
        self
    }

    pub fn no_network(mut self) -> Self {
        self.config.network = NetworkMode::None;
        self
    }

    pub fn unix_datagram_network(mut self, peer_path: impl Into<PathBuf>, mac: [u8; 6]) -> Self {
        self.config.network = NetworkMode::UnixDatagram {
            peer_path: peer_path.into(),
            mac,
        };
        self
    }

    pub fn disk(mut self, disk: DiskImage) -> Self {
        self.config.disks.push(disk);
        self
    }

    pub fn mount(mut self, mount: SharedDirectory) -> Self {
        self.config.mounts.push(mount);
        self
    }

    pub fn prepared_rosetta(mut self, config: crate::krun::RosettaLaunchConfig) -> Self {
        self.config.krun.prepared_rosetta = Some(config);
        self
    }

    pub fn rosetta(mut self, intent: RosettaIntent) -> Self {
        self.config.rosetta = intent;
        self
    }

    /// Persisted machine identity (macOS backend only; ignored elsewhere).
    pub fn machine_identifier(mut self, machine_identifier: MachineIdentifier) -> Self {
        self.config.vz.machine_identifier = Some(machine_identifier);
        self
    }

    pub fn build(self) -> VmConfig {
        self.config
    }
}

/// Structural checks every backend applies before constructing a machine.
pub(crate) fn validate_common(config: &VmConfig) -> Result<(), VirtError> {
    let invalid = |reason: String| VirtError::InvalidConfig {
        name: config.name.clone(),
        reason,
    };

    if config.name.is_empty() {
        return Err(invalid("machine name must not be empty".to_string()));
    }
    if config.base_directory.as_os_str().is_empty() {
        return Err(invalid("base directory must not be empty".to_string()));
    }
    if config.kernel_path.is_none() {
        return Err(invalid("a kernel image is required".to_string()));
    }
    if config.cpus == Some(0) {
        return Err(invalid("cpu count must be nonzero".to_string()));
    }
    if config.memory_mib == Some(0) {
        return Err(invalid("memory size must be nonzero".to_string()));
    }
    if config.rosetta != RosettaIntent::Disabled
        && config
            .mounts
            .iter()
            .any(|mount| mount.tag == agent_spec::ROSETTA_MOUNT_TAG)
    {
        return Err(invalid(format!(
            "mount tag {:?} is reserved for Rosetta",
            agent_spec::ROSETTA_MOUNT_TAG
        )));
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use crate::virt::config::*;

    fn base_builder() -> VmConfigBuilder {
        VmConfig::builder("test-vm")
            .vm_id("vm-1")
            .base_directory("/tmp/test-vm")
            .kernel("/tmp/test-vm/vmlinux")
    }

    #[test]
    fn builder_maps_backend_sections() {
        let identifier = MachineIdentifier::from_bytes(vec![1, 2, 3]);
        let config = base_builder()
            .rosetta(RosettaIntent::VzNative)
            .machine_identifier(identifier.clone())
            .build();

        assert_eq!(config.rosetta(), RosettaIntent::VzNative);
        assert_eq!(config.vz().machine_identifier, Some(identifier));
    }

    #[test]
    fn builder_collects_devices_in_order() {
        let config = base_builder()
            .disk(DiskImage {
                path: "/tmp/a.img".into(),
                read_only: false,
            })
            .disk(DiskImage {
                path: "/tmp/b.img".into(),
                read_only: true,
            })
            .mount(SharedDirectory {
                host_path: "/tmp/share".into(),
                tag: "share".into(),
                read_only: true,
            })
            .build();

        assert_eq!(config.disks().len(), 2);
        assert_eq!(config.disks()[0].path, PathBuf::from("/tmp/a.img"));
        assert!(config.disks()[1].read_only);
        assert_eq!(config.mounts()[0].tag, "share");
    }

    #[test]
    fn validate_common_accepts_minimal_config() {
        let config = base_builder().build();
        assert!(validate_common(&config).is_ok());
    }

    #[test]
    fn validate_common_rejects_missing_kernel() {
        let config = VmConfig::builder("test-vm")
            .vm_id("vm-1")
            .base_directory("/tmp/test-vm")
            .build();
        assert!(matches!(
            validate_common(&config),
            Err(VirtError::InvalidConfig { .. })
        ));
    }

    #[test]
    fn enabled_rosetta_reserves_its_share_tag() {
        let config = base_builder()
            .rosetta(RosettaIntent::VzNative)
            .mount(SharedDirectory {
                host_path: "/tmp/user-rosetta".into(),
                tag: agent_spec::ROSETTA_MOUNT_TAG.to_string(),
                read_only: true,
            })
            .build();

        let error = validate_common(&config).expect_err("reject reserved mount tag");
        assert!(error.to_string().contains("reserved for Rosetta"));
    }

    #[test]
    fn machine_identifier_write_back_marks_generated() {
        let identifier = MachineIdentifier::new();
        assert!(identifier.is_empty());
        assert!(!identifier.was_generated());

        identifier.set_generated_bytes(vec![7, 8, 9]);
        assert_eq!(identifier.bytes(), vec![7, 8, 9]);
        assert!(identifier.was_generated());
    }
}
